default:
  target: dev
  outputs:
    dev:
      account: OI08186.eu-west-3.aws
      database: demo_dbt
      password: "{{ env_var('dbt_password') }}"
      role: dbt_dev_role
      schema: public
      threads: 1
      type: snowflake
      user: "{{ env_var('dbt_user') }}"
      warehouse: dbt_dev_wh

